Use Reuqest class for making API requests
sendsmaily/smaily-opencart-module pull request #142
Opened 2020-12-18 16:11 UTC by TomAbel

#124

for OpenCart 1.5.6.4

realized this:
```
} catch (SmailyError $error) {
  $msg = $error->getMessage();
  $this->log->write($msg);
  echo($msg);
```
voids the purpose of `__toString()` in BaseError class. Having `$error->getMessage() ` would just print out _GET request to Smaily API failed_ which isn't very helpful. Modified it so we're writing and echoing the $error variable, properly formatted.

2020-12-18 18:38 UTC, kaittodesk requested changes

2020-12-18 18:38 UTC, kaittodesk commented on upload/admin/model/smailyforopencart/admin.php
> +
Formatting: excess empty line.

2020-12-18 18:38 UTC, kaittodesk commented on upload/admin/model/smailyforopencart/admin.php
> +
Formatting: excess empty line.

2020-12-21 05:47 UTC, TomAbel commented on upload/admin/model/smailyforopencart/admin.php
> +
Removed in 4fe0aac

2020-12-21 05:47 UTC, TomAbel commented on upload/admin/model/smailyforopencart/admin.php
> +
Removed in 4fe0aac

2020-12-21 07:11 UTC, kaittodesk approved these changes

2020-12-21 07:24 UTC, merged