Maint/release checklist 2.2.x
sendsmaily/smaily-opencart-module pull request #156
Opened 2020-12-21 12:15 UTC by TomAbel

changes necessary to release 1.5.0 for OpenCart 2.2.x

2020-12-21 13:36 UTC, kaittodesk requested changes

2020-12-21 13:36 UTC, kaittodesk commented on CHANGELOG.md
> +
Formatting: excessive empty line.

2020-12-22 11:28 UTC, TomAbel commented on CHANGELOG.md
> +
Added 
42c0648

2020-12-22 11:28 UTC, kaittodesk approved these changes

2020-12-22 11:29 UTC, merged